# Generated by Django 5.2.13 on 2026-05-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_mission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='completed',
        ),
        migrations.AddField(
            model_name='mission',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='mission_proofs/'),
        ),
        migrations.AddField(
            model_name='mission',
            name='proof_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
