# Generated by Django 5.2.13 on 2026-05-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_mission_completed_mission_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_active_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
