# Generated by Django 5.2.13 on 2026-05-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_player_last_active_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='avatars/'),
        ),
    ]
