# Generated by Django 5.2.13 on 2026-05-03 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_player_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='player',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='proof_image',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='proof_text',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='status',
        ),
        migrations.CreateModel(
            name='MissionSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('proof_text', models.TextField(blank=True)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='mission_proofs/')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.mission')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
            options={
                'unique_together': {('player', 'mission')},
            },
        ),
    ]
